import 'package:equatable/equatable.dart';
import 'package:flutter/cupertino.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:ecomly_client/core/common/app/riverpod/current_user_provider.dart';
import 'package:ecomly_client/core/common/entities/user.dart';
import 'package:ecomly_client/core/services/injection_container.dart';
import 'package:ecomly_client/core/utils/typedefs.dart';
import 'package:ecomly_client/src/user/domain/usecases/get_user.dart';
import 'package:ecomly_client/src/user/domain/usecases/get_user_payment_profile.dart';
import 'package:ecomly_client/src/user/domain/usecases/update_user.dart';

part 'auth_user_provider.g.dart';
part 'auth_user_state.dart';

/// Provider responsible for managing authenticated user operations.
///
/// It connects the domain use cases ([GetUser], [UpdateUser], [GetUserPaymentProfile])
/// with the UI layer by exposing methods that update the [AuthUserState].
///
/// States are updated before, during, and after async operations
/// to reflect the current status of user-related actions.
@riverpod
class AuthUser extends _$AuthUser {
  /// Initializes dependencies and sets the initial state.
  ///
  /// The optional [familyKey] is generated by Riverpod when this provider
  /// is declared as a family. It allows Riverpod to differentiate between
  /// multiple instances of the same provider, often useful when you want
  /// to scope state per widget or per screen.
  ///
  /// In this implementation it is not used, but it could be leveraged if
  /// different screens/widgets need isolated `AuthUser` states.
  @override
  AuthUserState build([GlobalKey? familyKey]) {
    _getUser = sl<GetUser>();
    _updateUser = sl<UpdateUser>();
    _getUserPaymentProfile = sl<GetUserPaymentProfile>();
    return const AuthUserInitial();
  }

  late GetUser _getUser;
  late UpdateUser _updateUser;
  late GetUserPaymentProfile _getUserPaymentProfile;

  /// Fetches a user by [userId].
  ///
  /// - Sets state to [GettingUserData] while loading.
  /// - On success: updates the [currentUserProvider] and emits [UserUpdated].
  /// - On failure: emits [AuthUserError].
  Future<void> getUserById(String userId) async {
    state = const GettingUserData();
    final result = await _getUser(userId);

    result.fold((failure) => state = AuthUserError(failure.errorMessage), (
      user,
    ) {
      ref.read(currentUserProvider.notifier).setUser(user);
      state = UserUpdated(user);
    });
  }

  /// Updates the user with given [userId] and [updateData].
  ///
  /// - Sets state to [UpdatingUserData] while processing.
  /// - On success: updates the [currentUserProvider] and emits [UserUpdated].
  /// - On failure: emits [AuthUserError].
  Future<void> updateUser({
    required String userId,
    required DataMap updateData,
  }) async {
    state = const UpdatingUserData();
    final result = await _updateUser(
      UpdateUserParams(userId: userId, updateData: updateData),
    );

    result.fold((failure) => state = AuthUserError(failure.errorMessage), (
      user,
    ) {
      ref.read(currentUserProvider.notifier).setUser(user);
      state = UserUpdated(user);
    });
  }

  /// Fetches the payment profile URL for the given [userId].
  ///
  /// - Sets state to [GettingUserPaymentProfile] while loading.
  /// - On success: emits [FetchedUserPaymentProfile].
  /// - On failure: emits [AuthUserError].
  Future<void> getUserPaymentProfile(String userId) async {
    state = const GettingUserPaymentProfile();
    final result = await _getUserPaymentProfile(userId);

    result.fold(
      (failure) => state = AuthUserError(failure.errorMessage),
      (paymentProfileUrl) =>
          state = FetchedUserPaymentProfile(paymentProfileUrl),
    );
  }
}
