import 'package:equatable/equatable.dart';
import 'package:flutter/widgets.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:ecomly_client/core/common/singletons/cache.dart';
import 'package:ecomly_client/core/services/injection_container.dart';
import 'package:ecomly_client/core/utils/global_keys.dart';
import 'package:ecomly_client/src/cart/domain/entities/cart_product.dart';
import 'package:ecomly_client/src/cart/domain/usecases/add_to_cart.dart';
import 'package:ecomly_client/src/cart/domain/usecases/change_cart_product_quantity.dart';
import 'package:ecomly_client/src/cart/domain/usecases/get_cart.dart';
import 'package:ecomly_client/src/cart/domain/usecases/get_cart_count.dart';
import 'package:ecomly_client/src/cart/domain/usecases/get_cart_product.dart';
import 'package:ecomly_client/src/cart/domain/usecases/initiate_checkout.dart';
import 'package:ecomly_client/src/cart/domain/usecases/remove_from_cart.dart';

part 'cart_provider.g.dart';
part 'cart_state.dart';

/// Provider responsible for managing cart operations.
///
/// It connects the domain use cases with the UI layer by exposing methods that
/// update the [CartState].
///
/// States are updated before, during, and after async operations to reflect
/// the current status of cart-related actions.
@riverpod
class CartAdapter extends _$CartAdapter {
  /// Initializes dependencies and sets the initial state.
  ///
  /// The optional [familyKey] is generated by Riverpod when this provider
  /// is declared as a family. It allows Riverpod to differentiate between
  /// multiple instances of the same provider, useful when you want to scope
  /// state per widget or per screen.
  ///
  /// In this implementation it is not used, but could be leveraged if
  /// different screens/widgets need isolated `CartAdapter` states.
  @override
  CartState build([GlobalKey? familyKey]) {
    _addToCart = sl<AddToCart>();
    _changeCartProductQuantity = sl<ChangeCartProductQuantity>();
    _getCart = sl<GetCart>();
    _getCartCount = sl<GetCartCount>();
    _getCartProduct = sl<GetCartProduct>();
    _removeFromCart = sl<RemoveFromCart>();
    _initiateCheckout = sl<InitiateCheckout>();
    return const CartInitial();
  }

  late AddToCart _addToCart;
  late ChangeCartProductQuantity _changeCartProductQuantity;
  late GetCart _getCart;
  late GetCartCount _getCartCount;
  late GetCartProduct _getCartProduct;
  late RemoveFromCart _removeFromCart;
  late InitiateCheckout _initiateCheckout;

  /// Adds a product to the user's cart.
  ///
  /// - Sets state to [AddingToCart] while processing.
  /// - On success: emits [AddedToCart] and refreshes the cart count.
  /// - On failure: emits [CartError].
  Future<void> addToCart({
    required String userId,
    required CartProduct cartProduct,
  }) async {
    state = const AddingToCart();

    final result = await _addToCart(
      AddToCartParams(userId: userId, cartProduct: cartProduct),
    );

    result.fold((failure) => state = CartError(failure.errorMessage), (_) {
      state = const AddedToCart();
      ref
          .read(cartAdapterProvider(GlobalKeys.cartCountFamilyKey).notifier)
          .getCartCount(Cache.instance.userId!);
    });
  }

  /// Updates the quantity of a product in the user's cart.
  ///
  /// - Sets state to [ChangingCartProductQuantity] while processing.
  /// - On success: emits [ChangedCartProductQuantity].
  /// - On failure: emits [CartError].
  Future<void> changeCartProductQuantity({
    required String userId,
    required String cartProductId,
    required int newQuantity,
  }) async {
    state = const ChangingCartProductQuantity();

    final result = await _changeCartProductQuantity(
      ChangeCartProductQuantityParams(
        userId: userId,
        cartProductId: cartProductId,
        newQuantity: newQuantity,
      ),
    );

    result.fold(
      (failure) => state = CartError(failure.errorMessage),
      (_) => state = const ChangedCartProductQuantity(),
    );
  }

  /// Fetches all products in the user's cart.
  ///
  /// - Sets state to [FetchingCart] while processing.
  /// - On success: emits [CartFetched].
  /// - On failure: emits [CartError].
  Future<void> getCart(String userId) async {
    state = const FetchingCart();

    final result = await _getCart(userId);

    result.fold(
      (failure) => state = CartError(failure.errorMessage),
      (cart) => state = CartFetched(cart),
    );
  }

  /// Fetches the total number of items in the user's cart.
  ///
  /// - Sets state to [FetchingCartCount] while processing.
  /// - On success: emits [CartCountFetched].
  /// - On failure: emits [CartError].
  Future<void> getCartCount(String userId) async {
    state = const FetchingCartCount();

    final result = await _getCartCount(userId);

    result.fold(
      (failure) => state = CartError(failure.errorMessage),
      (count) => state = CartCountFetched(count),
    );
  }

  /// Fetches a specific cart product by its ID.
  ///
  /// - Sets state to [FetchingCartProduct] while processing.
  /// - On success: emits [CartProductFetched].
  /// - On failure: emits [CartError].
  Future<void> getCartProduct({
    required String userId,
    required String cartProductId,
  }) async {
    state = const FetchingCartProduct();

    final result = await _getCartProduct(
      GetCartProductParams(userId: userId, cartProductId: cartProductId),
    );

    result.fold(
      (failure) => state = CartError(failure.errorMessage),
      (cartProduct) => state = CartProductFetched(cartProduct),
    );
  }

  /// Removes a product from the user's cart.
  ///
  /// - Sets state to [RemovingFromCart] while processing.
  /// - On success: emits [RemovedFromCart] and refreshes the cart count.
  /// - On failure: emits [CartError].
  Future<void> removeFromCart({
    required String userId,
    required String cartProductId,
  }) async {
    state = const RemovingFromCart();

    final result = await _removeFromCart(
      RemoveFromCartParams(userId: userId, cartProductId: cartProductId),
    );

    result.fold((failure) => state = CartError(failure.errorMessage), (_) {
      state = const RemovedFromCart();
      ref
          .read(cartAdapterProvider(GlobalKeys.cartCountFamilyKey).notifier)
          .getCartCount(Cache.instance.userId!);
    });
  }

  /// Initiates the checkout process for the user's cart.
  ///
  /// - Sets state to [InitiatingCheckout] while processing.
  /// - On success: emits [CheckoutInitiated] with the checkout URL.
  /// - On failure: emits [CartError].
  Future<void> initiateCheckout({
    required String theme,
    required List<CartProduct> cartItems,
  }) async {
    state = const InitiatingCheckout();

    final result = await _initiateCheckout(
      InitiateCheckoutParams(theme: theme, cartItems: cartItems),
    );

    result.fold(
      (failure) => state = CartError(failure.errorMessage),
      (sessionUrl) => state = CheckoutInitiated(sessionUrl),
    );
  }
}
