import 'package:equatable/equatable.dart';
import 'package:flutter/widgets.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:ecomly_client/core/services/injection_container.dart';
import 'package:ecomly_client/src/wishlist/domain/entities/wishlist_product.dart';
import 'package:ecomly_client/src/wishlist/domain/usecases/add_to_wishlist.dart';
import 'package:ecomly_client/src/wishlist/domain/usecases/get_wishlist.dart';
import 'package:ecomly_client/src/wishlist/domain/usecases/remove_from_wishlist.dart';

part 'wishlist_provider.g.dart';
part 'wishlist_state.dart';

/// Provider responsible for managing wishlist operations.
///
/// It connects the domain use cases with the UI layer by exposing methods that
/// update the [WishlistState].
///
/// States are updated before, during, and after async operations to reflect
/// the current status of wishlist-related actions.
@riverpod
class UserWishlist extends _$UserWishlist {
  /// Initializes dependencies and sets the initial state.
  ///
  /// The optional [familyKey] is generated by Riverpod when this provider
  /// is declared as a family. It allows Riverpod to differentiate between
  /// multiple instances of the same provider, useful when you want to scope
  /// state per widget or per screen.
  ///
  /// In this implementation it is not used, but could be leveraged if
  /// different screens/widgets need isolated `UserWishlist` states.
  @override
  WishlistState build([GlobalKey? familyKey]) {
    _getWishlist = sl<GetWishlist>();
    _addToWishlist = sl<AddToWishlist>();
    _removeFromWishlist = sl<RemoveFromWishlist>();
    return const WishlistInitial();
  }

  late GetWishlist _getWishlist;
  late AddToWishlist _addToWishlist;
  late RemoveFromWishlist _removeFromWishlist;

  /// Fetches all products in the user's wishlist.
  ///
  /// - Sets state to [GettingUserWishlist] while processing.
  /// - On success: emits [FetchedUserWishlist].
  /// - On failure: emits [WishlistError].
  Future<void> getWishlist(String userId) async {
    state = const GettingUserWishlist();
    final result = await _getWishlist(userId);
    result.fold(
      (failure) => state = WishlistError(failure.errorMessage),
      (wishlist) => state = FetchedUserWishlist(wishlist),
    );
  }

  /// Adds a product to the user's wishlist.
  ///
  /// - Sets state to [AddingToWishlist] while processing.
  /// - On success: emits [AddedToWishlist].
  /// - On failure: emits [WishlistError].
  Future<void> addToWishlist({
    required String userId,
    required String productId,
  }) async {
    state = const AddingToWishlist();
    final result = await _addToWishlist(
      AddToWishlistParams(userId: userId, productId: productId),
    );
    result.fold(
      (failure) => state = WishlistError(failure.errorMessage),
      (_) => state = const AddedToWishlist(),
    );
  }

  /// Removes a product from the user's wishlist.
  ///
  /// - Sets state to [RemovingFromWishlist] while processing.
  /// - On success: emits [RemovedFromWishlist].
  /// - On failure: emits [WishlistError].
  Future<void> removeFromWishlist({
    required String userId,
    required String productId,
  }) async {
    state = const RemovingFromWishlist();
    final result = await _removeFromWishlist(
      RemoveFromWishlistParams(userId: userId, productId: productId),
    );
    result.fold(
      (failure) => state = WishlistError(failure.errorMessage),
      (_) => state = const RemovedFromWishlist(),
    );
  }
}
