import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'package:ecomly_client/core/common/app/riverpod/current_user_provider.dart';
import 'package:ecomly_client/core/common/entities/user.dart';
import 'package:ecomly_client/core/services/injection_container.dart';
import 'package:ecomly_client/src/auth/domain/usecases/forgot_password.dart';
import 'package:ecomly_client/src/auth/domain/usecases/login.dart';
import 'package:ecomly_client/src/auth/domain/usecases/register.dart';
import 'package:ecomly_client/src/auth/domain/usecases/reset_password.dart';
import 'package:ecomly_client/src/auth/domain/usecases/verify_o_t_p.dart';
import 'package:ecomly_client/src/auth/domain/usecases/verify_token.dart';

part 'auth_adapter.g.dart';
part 'auth_state.dart';

/// Provider responsible for managing authentication operations.
///
/// It connects the domain use cases ([Login], [Register], [ForgotPassword],
/// [VerifyOTP], [ResetPassword], [VerifyToken]) with the UI layer by exposing
/// methods that update the [AuthState].
///
/// States are updated before, during, and after async operations to reflect the
/// current authentication status of the user.
@riverpod
class AuthAdapter extends _$AuthAdapter {
  /// Initializes dependencies and sets the initial state.
  ///
  /// The optional [familyKey] is generated by Riverpod when this provider
  /// is declared as a family. It allows Riverpod to differentiate between
  /// multiple instances of the same provider, often useful when you want
  /// to scope state per widget or per screen.
  ///
  /// In this implementation it is not used, but it could be leveraged if
  /// different screens/widgets need isolated `AuthAdapter` states.
  @override
  AuthState build([GlobalKey? familyKey]) {
    _forgotPassword = sl<ForgotPassword>();
    _login = sl<Login>();
    _register = sl<Register>();
    _resetPassword = sl<ResetPassword>();
    _verifyOTP = sl<VerifyOTP>();
    _verifyToken = sl<VerifyToken>();
    return const AuthInitial();
  }

  late ForgotPassword _forgotPassword;
  late Login _login;
  late Register _register;
  late ResetPassword _resetPassword;
  late VerifyOTP _verifyOTP;
  late VerifyToken _verifyToken;

  /// Attempts to log in with the given [email] and [password].
  ///
  /// - Sets state to [AuthLoading] while authenticating.
  /// - On success: updates [currentUserProvider] and emits [LoggedIn].
  /// - On failure: emits [AuthError].
  Future<void> login({required String email, required String password}) async {
    state = const AuthLoading();
    final result = await _login(LoginParams(email: email, password: password));

    result.fold((failure) => state = AuthError(failure.errorMessage), (user) {
      ref.read(currentUserProvider.notifier).setUser(user);
      state = LoggedIn(user);
    });
  }

  /// Registers a new user with the given [name], [email], [password], and [phone].
  ///
  /// - Sets state to [AuthLoading] while processing.
  /// - On success: emits [Registered].
  /// - On failure: emits [AuthError].
  Future<void> register({
    required String name,
    required String email,
    required String password,
    required String phone,
  }) async {
    state = const AuthLoading();
    final result = await _register(
      RegisterParams(
        name: name,
        password: password,
        email: email,
        phone: phone,
      ),
    );

    result.fold(
      (failure) => state = AuthError(failure.errorMessage),
      (_) => state = const Registered(),
    );
  }

  /// Sends a password reset OTP to the given [email].
  ///
  /// - Sets state to [AuthLoading] while sending.
  /// - On success: emits [OTPSent].
  /// - On failure: emits [AuthError].
  Future<void> forgotPassword({required String email}) async {
    state = const AuthLoading();
    final result = await _forgotPassword(email);

    result.fold(
      (failure) => state = AuthError(failure.errorMessage),
      (_) => state = const OTPSent(),
    );
  }

  /// Verifies the [otp] for the given [email].
  ///
  /// - Sets state to [AuthLoading] while verifying.
  /// - On success: emits [OTPVerified].
  /// - On failure: emits [AuthError].
  Future<void> verifyOTP({required String email, required String otp}) async {
    state = const AuthLoading();
    final result = await _verifyOTP(VerifyOTPParams(email: email, otp: otp));

    result.fold(
      (failure) => state = AuthError(failure.errorMessage),
      (_) => state = const OTPVerified(),
    );
  }

  /// Resets the password for the given [email] with [newPassword].
  ///
  /// - Sets state to [AuthLoading] while resetting.
  /// - On success: emits [PasswordReset].
  /// - On failure: emits [AuthError].
  Future<void> resetPassword({
    required String email,
    required String newPassword,
  }) async {
    state = const AuthLoading();
    final result = await _resetPassword(
      ResetPasswordParams(email: email, newPassword: newPassword),
    );

    result.fold(
      (failure) => state = AuthError(failure.errorMessage),
      (_) => state = const PasswordReset(),
    );
  }

  /// Verifies the current authentication token.
  ///
  /// - Sets state to [AuthLoading] while verifying.
  /// - On success: emits [TokenVerified].
  ///   - If token is invalid, also clears [currentUserProvider].
  /// - On failure: emits [AuthError].
  Future<void> verifyToken() async {
    state = const AuthLoading();
    final result = await _verifyToken();

    result.fold((failure) => state = AuthError(failure.errorMessage), (
      isValid,
    ) {
      state = TokenVerified(isValid);
      if (!isValid) ref.read(currentUserProvider.notifier).setUser(null);
    });
  }
}
